/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.util.Arrays;

public class App {

    private static final int[] arr = {15, 12, 20, 2, 4};
    private static final int[] arrEmpty = {};
    private static final int[] arrOne = {2};
    private static final QuickSort sortQ = new QuickSort();
    private static final MergeSort sortM = new MergeSort();

    public static void main(String[] args) {


//        InsertionSort sort = new InsertionSort();
//        sort.selectionSort(arr);
//        sort.selectionSort(arrEmpty);
//        sort.selectionSort(arrOne);
//
//        System.out.println("Selection sort "+ Arrays.toString(arr));
//        System.out.println("Selection sort "+ Arrays.toString(arrEmpty));
//        System.out.println("Selection sort "+ Arrays.toString(arrOne));
//
//
//        sort.selectionSortDescending(arr);
//        System.out.println("Selection sort Descending "+ Arrays.toString(arr));

        sortQ.quickSort(arr);
        System.out.println("Quick sort" + Arrays.toString(arr));
        sortM.mergeSort(arr);
        System.out.println("Merge sort" + Arrays.toString(arr));


    }
}
