/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] arr = { 15, 12, 20, 2, 4 };

        QuickSort sort = new QuickSort();
        sort.quickSort(arr);

        System.out.println("Quick sort"+ Arrays.toString(arr));

}
}
