/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");
        graph.addVertex("Noor");


        graph.addEdge("Bob", "Mary");
        graph.addEdge("Bob", "Alice");
        graph.addEdge("Alice", "Bob");
        graph.addEdge("Alice", "Noor");
        System.out.println( graph.size());

        System.out.println( graph.printGraph());
        graph.removeVertex("Bob");
        graph.removeEdge("Alice","Noor");
        System.out.println( graph.printGraph());
        System.out.println( graph.size());






    }
}
