/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph graph = new Graph();
//        graph.addNode("Bob");
        graph.addNode("Alice");
//        graph.addNode("Mary");
        graph.addNode("Noor");
//
//
//        graph.addEdge("Bob", "Mary");
//        graph.addEdge("Bob", "Alice");
//        graph.addEdge("Alice", "Bob");
//        graph.addEdge("Alice", "Noor");
        graph.addEdge("Noor", "Alice");
//        System.out.println(graph);
        System.out.println( graph.printGraph());
//        graph.removeVertex("Bob");
//        graph.removeEdge("Alice","Noor");
//        System.out.println( graph.printGraph());
//        System.out.println( graph.size());
        System.out.println( graph.getNeighbors("Noor"));
        System.out.println( graph.getNodes());







    }
}
