/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import stackQueue.QueueLinkedList;
import stackQueue.StackLinkedList;
import stackQueue.pseudoQueue;

public class App {
    private static final StackLinkedList<Integer> stackList = new StackLinkedList<Integer>();
    private static final pseudoQueue<Integer> pseudoQueueList = new pseudoQueue<>();


    public static void main(String[] args) {
        QueueLinkedList<Integer> queueList = new QueueLinkedList<Integer>();

        // 1. Stack
//        System.out.println("stackList: " + stackList);
//        stackList.push(10);
//        stackList.push(15);
//        stackList.push(20);
//
//        System.out.println("stackList: " + stackList);
//        System.out.println(stackList.peek());
//        System.out.println("stackList isEmpty: "+ stackList.isEmpty());
//
//        System.out.println("pop 3: " + stackList.pop());
//        System.out.println("pop 2: "+ stackList.pop());
//        System.out.println("pop 1: "+ stackList.pop());
//
//        System.out.println("stackList isEmpty: "+ stackList.isEmpty());
//        System.out.println(stackList.peek());
//
//        // 2. Queue
//        System.out.println(queueList);
//
//        queueList.enqueue(1);
//        queueList.enqueue(2);
//        queueList.enqueue(3);
//
//        System.out.println("Queue list: " + queueList);
//        System.out.println("queueList.isEmpty(): " + queueList.isEmpty());
//
//        System.out.println("dequeue 1: " + queueList.dequeue());
//        System.out.println("dequeue 2: " + queueList.dequeue());
//        System.out.println("dequeue 3: " + queueList.dequeue());
//
//
//        System.out.println("Queue list: " + queueList);
//
//
//        System.out.println("Queue list is empty: " + queueList.isEmpty());
//
//        System.out.println("Queue list peek(): " + queueList.peek());
//
        System.out.println(pseudoQueueList);
//        pseudoQueueList.enqueue(20);
//        pseudoQueueList.enqueue(15);
//        pseudoQueueList.enqueue(10);


//        pseudoQueueList.enqueue(5);
//        pseudoQueueList.enqueue(5);
//        pseudoQueueList.enqueue(6);
//        pseudoQueueList.enqueue(7);
//
        System.out.println(pseudoQueueList);

        System.out.println("dequeue: " + pseudoQueueList.dequeue());
//
//        System.out.println(pseudoQueueList);


    }
}
