/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import stackQueue.QueueLinkedList;
import stackQueue.StackLinkedList;

public class App {
    private static final StackLinkedList<Integer> stackList = new StackLinkedList<Integer>();

    public static void main(String[] args) {
        QueueLinkedList<Integer> queueList = new QueueLinkedList<Integer>();

        // 1. Stack
        System.out.println("stackList: " + stackList);
//        stackList.push(1);
//        stackList.push(2);
//        stackList.push(3);

        System.out.println("stackList: " + stackList);
//        System.out.println(stackList.peek());
//        System.out.println("stackList isEmpty: "+ stackList.isEmpty());
//
        System.out.println("pop 3: " + stackList.pop());
//        System.out.println("pop 2: "+ stackList.pop());
//        System.out.println("pop 1: "+ stackList.pop());
//
//        System.out.println("stackList isEmpty: "+ stackList.isEmpty());
//        System.out.println(stackList.peek());
//
//        // 2. Queue
//        System.out.println(queueList);
//
//        queueList.enqueue(1);
//        queueList.enqueue(2);
//        queueList.enqueue(3);
//
//        System.out.println("Queue list: " + queueList);
//        System.out.println("queueList.isEmpty(): " + queueList.isEmpty());
//
        System.out.println("dequeue 1: " + queueList.dequeue());
//        System.out.println("dequeue 2: " + queueList.dequeue());
//        System.out.println("dequeue 3: " + queueList.dequeue());
//
//
//        System.out.println("Queue list: " + queueList);
//
//
//        System.out.println("Queue list is empty: " + queueList.isEmpty());
//
//        System.out.println("Queue list peek(): " + queueList.peek());
//


    }
}
