/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class App {

    public static void main(String[] args) {
        HashTable<String, Integer> studentsMoney = new HashTable<>();
        studentsMoney.add("Noor", 200);
        studentsMoney.add("Sara", 300);

        System.out.println("The size is => " + studentsMoney.getSize());
        System.out.println("The Noor money is => " + studentsMoney.get("Noor"));

    }
}
